# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3576a1c0f9032efc573b79a288323206b5e02118bbfb87807d09997da57c0b4d9a3a9df8063954b392e40da15f3af051f18589f34c64e7becb9cf4992faca58c

test:
  secret_key_base: 7bbc1faa93a52de1d5e357f282f8ad0b5fb631c68d0d5c70a8f672dde157f0cd9524c409d55959ce637d68dbba8202d92b7c6688db38469d4f69e2abef1e1c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
